/* Matthew Bergamini 8137225 */
USE csit115;

SELECT * FROM EMPLOYEE;

/* Question 1 */
SELECT FNAME,LNAME FROM EMPLOYEE WHERE STATE='NSW' OR SUBURB='Hurstville' OR STREET='Victoria St.' OR STREET='Pennant Hills.';

/* Question 2 */
SELECT REGNUM, CAPACITY, STATUS FROM TRUCK WHERE CAPACITY >=2000 OR CAPACITY <= 4000;

/* Question 3 NOW WORKING*/
SELECT FNAME, LNAME FROM EMPLOYEE WHERE INITIALS IS NULL OR DOB IS NOT NULL;

/* Question 4 */
/* SELECT LEFT(DOB, 4) AS YEAR FROM EMPLOYEE; */
SELECT FNAME, LNAME FROM EMPLOYEE WHERE LEFT(DOB, 4) = 1980 OR LEFT(DOB, 4) = 1992;

/* Question 5 */
SELECT REGNUM, STATUS
FROM TRUCK
ORDER BY STATUS ASC, REGNUM DESC;


/* Question 6 */
SELECT COUNT(DISTINCT TL.DEPARTURE) AS "Total Cities with Departures"
FROM TRIPLEG TL
WHERE TL.LEGNUM = 1;


/* Question 7 */
SELECT D.LNUM AS "License Number", COUNT(T.TNUM) AS "Total Trips" FROM DRIVER D
INNER JOIN TRIP T ON D.LNUM = T.LNUM
GROUP BY D.LNUM
HAVING COUNT(T.TNUM) > 0;

/* QUESTION 8 */
SELECT T.REGNUM, COUNT(TL.TNUM) AS TotalTrips
FROM TRUCK T
LEFT JOIN TRIP TR ON T.REGNUM = TR.REGNUM
LEFT JOIN TRIPLEG TL ON TR.TNUM = TL.TNUM
GROUP BY T.REGNUM
HAVING TotalTrips > 5;


/* Question 9  Date is werid YYYY/MM/DD*/
SELECT TR.TNUM, D.LNUM, TR.REGNUM
FROM TRIP TR
JOIN DRIVER D ON TR.LNUM = D.LNUM
WHERE TR.TDATE BETWEEN '2016-01-01' AND DATE_ADD('2016-01-01', INTERVAL 30 DAY);


/* Question 10 */
SELECT CityName, COUNT(*) AS "Cities Passed Through"
FROM (
    SELECT DEPARTURE AS CityName FROM TRIPLEG
    UNION ALL
    SELECT DESTINATION AS CityName FROM TRIPLEG
) AS AllCities
WHERE CityName LIKE '%y%'
GROUP BY CityName;







