/* Matthew Bergamini 8137225 */
USE csit115;

/* Question 1 */
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE ENUM IN (
    SELECT ENUM
    FROM DRIVER
    WHERE STATUS = 'ON LEAVE'
);


/* Question 2 */
SELECT DISTINCT REGNUM
FROM TRUCK T
WHERE STATUS = 'USED'
  AND EXISTS (
    SELECT 1
    FROM TRIP
    WHERE REGNUM = T.REGNUM
      AND YEAR(TDATE) = 2016
  );


/* Question 3 */
SELECT FNAME, LNAME
FROM EMPLOYEE E
WHERE NOT EXISTS (
    SELECT 1
    FROM DRIVER D
    WHERE E.ENUM = D.ENUM
);


/* Question 4 */
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE ENUM IN (
    SELECT LNUM
    FROM TRIP
    WHERE YEAR(TDATE) = 2017
    UNION
    SELECT ENUM
    FROM DRIVER
);


/* Question 5 */
SELECT DISTINCT CITY
FROM (
    SELECT DEPARTURE AS CITY
    FROM TRIPLEG
    WHERE TNUM IN (1, 8)
    UNION
    SELECT DESTINATION AS CITY
    FROM TRIPLEG
    WHERE TNUM IN (1, 8)
) AS CityList;


/* Question 6 */
SELECT DISTINCT CITY
FROM (
    SELECT DEPARTURE AS CITY
    FROM TRIPLEG
    WHERE TNUM = 1
    AND EXISTS (
        SELECT 1
        FROM TRIPLEG
        WHERE TNUM = 8
        AND DEPARTURE = TRIPLEG.DEPARTURE
    )
    UNION
    SELECT DESTINATION AS CITY
    FROM TRIPLEG
    WHERE TNUM = 1
    AND EXISTS (
        SELECT 1
        FROM TRIPLEG
        WHERE TNUM = 8
        AND DESTINATION = TRIPLEG.DESTINATION
    )
) AS CommonCities;
